---
# tasks file for node_versionmanager-installation
- name: Install required dependencies for Debian/Ubuntu
  ansible.builtin.apt:
    name:
      - curl
      - build-essential
      - libssl-dev
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install required dependencies for RedHat/CentOS
  ansible.builtin.yum:
    name:
      - curl
      - gcc
      - openssl-devel
      - make
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Download and install NVM (Node Version Manager)
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  args:
    creates: ~/.nvm/nvm.sh

- name: Load NVM and install Node.js (latest LTS version)
  ansible.builtin.shell: >
    source ~/.nvm/nvm.sh && nvm install --lts
  args:
    executable: /bin/bash
  environment:
    NVM_DIR: "{{ ansible_env.HOME }}/.nvm"

- name: Verify Node.js installation
  ansible.builtin.shell: >
    source ~/.nvm/nvm.sh && node --version
  register: node_version
  args:
    executable: /bin/bash
  environment:
    NVM_DIR: "{{ ansible_env.HOME }}/.nvm"

- name: Display Node.js version
  ansible.builtin.debug:
    msg: "Installed Node.js version: {{ node_version.stdout }}"

